version: '3.8'

services:
  mariadb:
    image: arm64v8/mariadb  # ARM-compatible MariaDB image
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password for MariaDB
      MYSQL_DATABASE: mydatabase  # Name of a database to create on startup
      MYSQL_USER: user  # Username for a non-root user
      MYSQL_PASSWORD: userpassword  # Password for the non-root user
    ports:
      - "3306:3306"  # Expose the default MariaDB port
    volumes:
      - mariadb_data:/var/lib/mysql  # Persistent storage for database data

  adminer:
    image: adminer  # Adminer image for the GUI
    container_name: adminer
    ports:
      - "8080:8080"  # Expose Adminer on port 8080
    depends_on:
      - mariadb  # Ensure MariaDB starts before Adminer

volumes:
  mariadb_data:
